version: "3"

services:
    rabbitmq:
        image: rabbitmq:3-management
        hostname: "rabbitmq"
        environment: 
            - RABBITMQ_DEFAULT_USER=admin
            - RABBITMQ_DEFAULT_PASS=mypass
        ports:
            - "15672:15672"
            - "5672:5672" 
    web:
        build: .
        ports:
            - "3000:3000"
        volumes:
            - .:/app
        environment:
            - ENV=development
            - PORT=3000
            